name: Release
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      dry-run:
        description: "Compiles the app but not upload artifacts to distribution server"
        default: false
        required: false
        type: boolean

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: "bash"

jobs:
  build:
    permissions:
      contents: write # Allows this job to create releases

    strategy:
      # fail-fast: true
      matrix:
        os: [windows-latest]
        # os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   if: matrix.os == 'macos-latest'
      #   with:
      #     python-version: "3.11"

      - name: Install appdmg for macOS
        if: matrix.os == 'macos-latest'
        run: yarn add -D appdmg

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # - name: Install Dependencies
      #   run: npm ci

      - name: Package Electron App
        run: yarn run package

      - name: Build Electron App
        run: yarn run make

      - name: Publish
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.os }}-artifacts
      #     path: out/make/**

      # - name: Archive Production Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ptz-controller
      #     path: out/make/**/*
      #   env:
      #     # Code Signing params
      #     # See https://www.electron.build/code-signing
      #     # CSC_LINK: ''
      #     # CSC_KEY_PASSWORD: ''
      #     # Publishing artifacts
      #     GH_TOKEN: ${{ secrets.github_token }} # GitHub token, automatically provided (No need to define this secret in the repo settings)
